Custom definitions for AudioAnalyzer.
roblox-ts/types pull request #1180
Opened 2024-02-23 21:06 UTC by Neohertz

Added custom definitions for both `GetSpectrum()` and `Changed`.

2024-02-23 21:12 UTC, osyrisrblx requested changes

2024-02-23 21:12 UTC, osyrisrblx commented on include/customDefinitions.d.ts
> +	readonly Changed: RBXScriptSignal<(value: string) => void>;
`Changed` is actually from `Instance`.. but we intentionally omit it because it breaks inheritance.

You should try to use `.GetPropertyChangedSignal()` when possible.

If that doesn't work, there's a helper type called `ChangedSignal` for this purpose. Here's an [example](https://roblox-ts.com/playground/#code/MYewdgzgLgBAhgVwCYEsQEExwDYE8BeApgE4wC8MYhA7jAJKRRxjCEAUAROsmpjgSQ4BKANwAoMW0SoMWPEVJwIMKLgAOhEADN4PWfwUwAZDADCAC2YBzQkgDKKK3KEA6C9dtvwVYFDZriEA1iVQA5OABbQnIAPhgAbzEASACUMD8AAwASeICgkjDIwgBfGGBLMBskAEIM0TFi+qA).

2024-02-23 21:16 UTC, Neohertz commented on include/customDefinitions.d.ts
> +	readonly Changed: RBXScriptSignal<(value: string) => void>;
Gotcha! I'll remove that real quick

2024-02-23 21:30 UTC, osyrisrblx requested changes
I try to keep the interfaces in `customDefinitions.d.ts` alphabetically sorted as much as possible. Can you move it higher please?

2024-02-24 04:08 UTC, osyrisrblx approved these changes

2024-02-24 04:08 UTC, merged