Use conditional type for pairs() return
roblox-ts/types pull request #792
Opened 2022-11-19 21:47 UTC by Dionysusnu

Fixes issues when providing a union, eg `pairs(a)` where `a: Map<Instance, unknown> | Set<Instance>`.
[Current behaviour with overloads](https://roblox-ts.com/playground/#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwFsBPAByixgGcAeAFQD4AKAKAEgcAjAK3AwC54AJRBRgeCEQCCMGFCJ16AGmYBKAQEkMIWRwggAYmky5U1ADLIotZCT3UA2qmQEO2xfACiAD0jJQddzRQRCxUEGB6AF16egBuZlBIWAQUdGw8QlJyKgVGTh5MAWFRcSIAZRAMBTV4TW0oXQMjdNMLKxs7e1p3DBhkEGi4hPBoOCRmk0yyChoAaXcANSY2fN4ikTFUCQBZKBJqefgl5Rq6nT1DNJNzS2tbEAdvX39DoJAQsIj3J4g-B4XAqhgqFwlEYvFEqMUhMMsRpjlaPAQF4tEDKPBVphluxuGt4N1VAIANYgIg4RD4pEokBo+BhABu2jYAH5alpzk0rngbu17g40ETUDgAO6odzAz6DNgadkNC4w1q3DoPewkskU7qeHy-fy0VWk8n4yKAiWgwbxZhw7KURhhYXwXb7JwuNzwSi9UIAcyYKhU8StM1tIHtFSq6lQ7qg6BAPr9zGGSTGYDw7vgUAEjuo4cj0fcAG8AL70eAAH3goazEYwUbAMfiiBwMHgjGTVfg9g47jAkQxFIDVEYUF98DzbA48VYYHiBeYQA)
[New behaviour with conditional type](https://roblox-ts.com/playground/#code/C4TwDgpgBACghgSwE4GcASEA2kkB4AqAfFALxT5QQAewEAdgCYpQBKEcDA9nZiAIJIkcELgR0AZhCRQAaoQBQASAD8UANp0ArgFsARlIA0UAKJUAxpk0MIuGUc2MI4sRAaEAukoBc5SjXpMrOxcPCAAyhDAohJSUADSCirqcUbASJoQnoo+FNS0jMxsHNy8ALJwYNGS0ilQYtWyiapqtaYWVjZ2UA7WznSuHt5QANYQIJzivnkBzP0AblJKzQ7DdJwA7nRGvS4MWT5qo+OT+EZtltYEh2MT5O72jn0D7gDc8vLWFnBI0OIOZsAENwoNpwIhUARCAAKTi6ABWEABOQAlD4AJK0IS6TAQABi-0B3FwABlNHB8JowDjcPBkOgsDhIYRCG95KCwOCUFD+usoOVKlo9IYoCg0mIAObQ5HIt7sznciC8iJRNF0UVwOhmCBSmXvT6Yb7QMzcUVQOA+fm4VXqzUQIwAbwAvsQAD5QZVWtXADValnycScaRQ41e9S6IxmdxQW5yulQuDSqD2pS6N6KMxvR3yIA)

2022-11-21 03:42 UTC, osyrisrblx requested changes

2022-11-21 03:42 UTC, osyrisrblx commented on include/lua.d.ts
> +		: [keyof T, Exclude<T[keyof T], undefined>];
Since this is only used in one place, maybe we should just inline it?

2022-11-21 03:45 UTC, Dionysusnu commented on include/lua.d.ts
> +		: [keyof T, Exclude<T[keyof T], undefined>];
I feel like inlining may look quite bulky and intrusive when the intellisense popup tries to show it?

2023-06-07 01:20 UTC, Dionysusnu commented
Needs reconsideration: discussed at https://discord.com/channels/476080952636997633/1109401600834945054

2023-06-07 01:20 UTC, closed without merging